### ISSUE TITLE
Add to write_file option for writing parameters in order

### ISSUE THREAD

**Issue by pavelsr** [rjbs/Config-INI#11]
Is there any possibility to write parameters in alphabetic order ?

Example:

```bash
$ cat rand.pl 
use Data::Random qw(rand_chars);
use Data::Dumper;
use Config::INI::Writer;

sub _get_rand {
	return rand_chars( set => 'loweralpha', min => 3, max => 5 );
}

my $h = { 'group1' => {} };
$h->{'group1'}{_get_rand()} = _get_rand() for (1..3);

warn Dumper $h;

Config::INI::Writer->write_file( $h, 'test.ini');

================================================

$ perl rand.pl 
$VAR1 = {
          'group1' => {
                        'wjdb' => 'hmix',
                        'fxtgz' => 'lst',
                        'jkx' => 'dfrus'
                      }
        };

================================================

$ cat test.ini 
[group1]
wjdb = hmix
fxtgz = lst
jkx = dfrus

```

Wanted result:

```bash
$ cat test.ini 
[group1]
jkx = dfrus
fxtgz = lst
wjdb = hmix
```

As I see from source code, [Config::INI::Writer::write_file](https://metacpan.org/pod/Config::INI::Writer#write_file) is inherited from [Mixin::Linewise::Writers::write_file ](https://metacpan.org/pod/release/RJBS/Mixin-Linewise-0.108/lib/Mixin/Linewise/Writers.pm#write_file)

It has `$options` :

```perl
Your::Pkg->write_file($data, $options, $filename);
```

Regarding [documentation](https://metacpan.org/pod/release/RJBS/Mixin-Linewise-0.108/lib/Mixin/Linewise/Writers.pm#write_file),

> An optional hash reference may be passed before $filename with options. The only valid option currently is binmode, which overrides any default set from use or the built-in encoding(UTF-8).

Don't you think that is could be useful to implement somewhere [here](https://metacpan.org/source/RJBS/Mixin-Linewise-0.108/lib/Mixin/Linewise/Writers.pm#L86) `$option` that can sort output ?

**Comment by eserte** [comment]
Another solution would be to use a tied hash which makes sure that `keys` and `each` are done in a defined order (in your case: alphabetic order). For example, you could use `Tie::Hash::Sorted`:

```
...
use Tie::Hash::Sorted;
tie my %group, 'Tie::Hash::Sorted';
my $h = { 'group1' => \%group };
...
```

Only problem here: `Tie::Hash::Sorted` is broken for recent perls, see https://rt.cpan.org/Public/Bug/Display.html?id=98320
Probably the problem is easy to fix (and maybe somebody could take over the module as it looks orphaned).

**Comment by rjbs** [comment]
The short version is that I have never really needed or wanted this, but it would be easy to write.  Config::INI is written to be subclassed.  You can easily write a Config::INI::Writer subclass that has a `preprocess_input` method that does the sorting you want.
